### ISSUE TITLE
recomendaciones

### ISSUE THREAD

**Issue by profesorfaco** [bennett-martin/dno-clase8-05-05#1]
Hola. Basándome en pauta de evaluación, algunas recomendaciones: 

**En index.html**, para lograr el efecto de fusión con imagen recortada y fondo, podrías probar con otra, por ejemplo:

https://i.pinimg.com/originals/fa/d7/a2/fad7a26d0d24a5a2b275960debf748d1.jpg

**En pelicula.htm**l, tendrías que cambiar la parte del texto que dice "Puedes ver algunas escenas de la película en Youtube". No se trata de película.

**En locaciones.html**, para llegar a los 5 que pide la pauta. Podrías marcarte como jugador en Santiago y alguien que conozcas a alguna otra parte del mundo… Así también puedes usar otro pin.

**En ganancias.html** no olvides el cambio en la leyenda (# of Votes).

**Comment by bennett-martin** [comment]
Gracias profe!! Un comentario eso si, en locaciones.html hay 5 locaciones, lo qué pasa es que las 3 qué hay en Japón están muy cerca una de la otra, hare los otros cambios de inmediato
